import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={` ${inter.className}`}>
        <main className="max-w-sm flex justify-center bg-[#FBF5F2] items-center min-h-screen mx-auto flex-col px-6 text-center relative ">
          {children}
        </main>
      </body>
    </html>
  );
}
